### ISSUE TITLE
[Task] Mypage

### ISSUE THREAD

**Issue by SangKwon-Lee** [codestates/nuga-the-sam-client#12]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: fix actions from client redux

### TODO
1. [x] request GET using Headers:Token
2. [x] render nickname, email, created_at
3. [x] render Comments and fights written by yourself
4. [x] Fights render when clicking a comments and fights

### Labels
- Estimated time: `E: 3h`
- Group : `client`
