### ISSUE TITLE
[Task] style 구현

### ISSUE THREAD

**Issue by lovvp** [codestates/nuga-the-sam-client#18]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: fix actions from client redux

### TODO
1. [ ] 컴포넌트별 CSS 구성
2. [ ] 페이지별 컴포넌트 구축
3. [ ] 알맞게 렌더링 되는지 확인하기

### Labels
- Estimated time: `E: 3h`
- Group : `client`
