### ISSUE TITLE
[Task] 로그인을 정상적으로 했을 경우 서버에서 요청을 받기 전까지 로딩화면을 모달창으로 뜨게 하는 기능

### ISSUE THREAD

**Issue by SangKwon-Lee** [codestates/nuga-the-sam-client#33]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 로그인을 정상적으로 했을 경우 서버에서 요청을 받기 전까지 로딩화면을 모달창으로 뜨게 하는 기능

### TODO
1. [x] 로그인 모달창 만들기 
2. [x] 서버에 요청 보내고 난 후 Loding화면을 모달창으로 뜨게 한다.
3. [x] 로그인이 성공적으로 됐을 경우 Loding 모달창이 사라지고 메인 페이지로 돌아간다. 

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 2h`
- Group : `client`
