### ISSUE TITLE
[Task] 마이페이지에서 닉네임 변경 요청 만들기

### ISSUE THREAD

**Issue by SangKwon-Lee** [codestates/nuga-the-sam-client#34]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 마이페이지에서 닉네임 변경 요청 만들기

### TODO
1. [ ] 마이페이지에서 유저 정보를 모두 받아오기.
2. [ ] 닉네임 변경 버튼 만들기.
3. [ ] 포스트 요청으로 서버에 변경된 닉네임 보내기
4. [ ] 서버에서 응답이 오기 전까지 로딩 모달창 만들기
5. [ ] 서버에서 응답받은 내용으로 마이페이지 수정

### Labels
- Estimated time: `E: 3h`
- Group : `client`
