### ISSUE TITLE
[Task] 게시글 페이지 Left/Right 제목 및 버튼 클릭스 추천 수 +1 기능 구현

### ISSUE THREAD

**Issue by SangKwon-Lee** [codestates/nuga-the-sam-client#35]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 게시글 페이지 Left/Right 제목 및 버튼 클릭스 추천 수 +1 기능 구현

### TODO
1. [ ] 게시글 페이지를 클릭스 get요청으로 데이터를 받아온다.
2. [ ] 받아온 데이터 중에서 LEFT / RIGHT 제목을 버튼으로 만든다. 
3. [ ] 그 버튼을 클릭시 LEFT VOTE / RIGHT VOTE가 +1이 된다.
4. [ ] 둘 중 하나를 투표했을 경우 투표한 버튼에 css로 표시해준다.
5. [ ] 둘 중 하나를 투표했을 경우 다른 곳에 투표를 하거나, 한 번 더 투표를 할 경우 모달창으로 "이미 투표하셨습니다" 메시지를 띄운다.

### Labels
- Estimated time: `E: 3h`
- Group : `client`
