### ISSUE TITLE
[Task] 게시글 페이지에 댓글 작성 기능 구현

### ISSUE THREAD

**Issue by SangKwon-Lee** [codestates/nuga-the-sam-client#36]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 게시글 페이지에 댓글 작성 기능 구현

### TODO
1. [ ] 게시글 페이지 하단 부분에 댓글 작성할 수 있는 text box 만들기 
2. [ ] 댓글 작성후 "작성" 버튼을 클릭하면 서버에 POST 요청
3. [ ] 투표한 사람만 댓글 작성할 수 있도록 알고리즘 구성
4. [ ] 요청이 완료되면 "댓글이 올라가는 중.." 등의 메시지를 모달창으로 띄움
5. [ ] 서버에 정상적으로 올라가면 GET요청을 통해 댓글을 띄움
6. [ ] 댓글에 LEFT / RIGHT인지 구별할 수 있는 요청도 같이 보냄
7. [ ] LEFT를 투표한 댓글이면 왼쪽 편에 댓글 랜더, RIGHT에 투표한 댓글이면 오른쪽 편에 댓글  랜더
8. [ ] 수정 기능 구현
9. [ ] 수정 버튼 클릭 시 모달 창으로 수정할 댓글 작성할 수 있도록
10. [ ] 수정한 댓글 요청의 POST 와 GET은 위와 같음.

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 3h`
- Group : `client`
