### ISSUE TITLE
[Task] Hot topic 

### ISSUE THREAD

**Issue by lovvp** [codestates/nuga-the-sam-client#5]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: make hot topic components
### TODO
1. [x] request Get to fights
2. [x] render response by all votes count
3. [x] if click card, change page of specific fights 

### Labels
- Estimated time: `E: 3h`
- Group : `client`
