### ISSUE TITLE
[Task] Now Topic

### ISSUE THREAD

**Issue by lovvp** [codestates/nuga-the-sam-client#6]
### ISSUE
- Group:  `client`, `server`, `sr`
- Type: `bug`, `feature`, `delete`
- Detail: fix actions from client redux

### TODO
1. [x] request Get to fights
2. [x] render response by created_at
3. [x] if click card, change page of specific fights 

### Labels
- Estimated time: `E: 3h`
- Group : `client`
