### ISSUE TITLE
[Task] Category menu

### ISSUE THREAD

**Issue by lovvp** [codestates/nuga-the-sam-client#7]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: make category menu

### TODO
1. [x] request GET all category
2. [x] make category button
3. [x] render category button
4. [x] if click category button, render fights

### Labels
- Estimated time: `E: 3h`
- Group : `client`
