### ISSUE TITLE
[Task] make header and footer

### ISSUE THREAD

**Issue by lovvp** [codestates/nuga-the-sam-client#8]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: make and render header and footer

### TODO
1. [x] make header component
2. [x] render logo to header
3. [x] render login button to header
4. [ ] make footer component
5. [ ] render kogong-pirates 

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 0.5h`
- Group : `client`
