### ISSUE TITLE
[Task] logout

### ISSUE THREAD

**Issue by SangKwon-Lee** [codestates/nuga-the-sam-client#9]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: fix actions from client redux

### TODO
1. [x] make logout button
2. [x] Change to logout button when login is successful
3. [x] request POST
4. [x] Change to login button when logout is successful

### Labels
- Estimated time: `E: 1h`
- Group : `client`
